################################################
# ━━━┳━━━╮
# ┃╭━╮┃╭━╮┃
# ┃┃╱╰┫╰━╯┣━━╮   Version: 1.0.0
# ┃┃╭━┫╭━━┫━━┫   Author: brihtakai
# ┃╰┻━┃┃╱╱┣━━┃
# ╰━━━┻╯╱╱╰━━╯
################################################

# ERRORS
no_player: "&cYou need to choose player."
no_number: "&cYou need to specify how much claim blocks do you want to send."
no_blocks: "&cYou dont have enought claim blocks!"
player_not_found: "&cSorry! We couldn't find that player!"
usage: "&4Usage: /gpsend <player> <number>"

# MESSAGES
sender: "&aYou send {number} claimblocks to {target}."
receiver: "&a{player} just sent you {number} claim blocks."
